import React, { useEffect, useState } from 'react'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import { useNavigate } from 'react-router-dom'
import axios from 'axios'
import { lists } from '../libs/api'

export default function Home() {
  const [loading, setIsLoading] = useState(false)
  const [allList, setList] = useState([])
  const [search, setSearch] = useState('')
  const navigate = useNavigate()
  const token = localStorage.getItem('token')
  
  useEffect(() => {
    if (!token) {
      navigate('/')
    } else {
      axios.defaults.headers.common['Authorization'] = token
      loadLists()
    }
  }, [])

  const loadLists = async (page) => {
    const response = await lists(page)
    if (response.data) {
      setList(response.data.data)
    } else {
      console.log(response.response.data.message)
    }
  }

  return (
    <>
    <Navbar />
    <section className='mx-5 md:container md:mx-auto md:px-48 mt-10 mb-10'>
      <div>
        <h1 className='font-extrabold text-3xl'>The Community Showcase</h1>
        <p className='mt-2 text-gray-500 text-xl'>Browse through of imaginative and visually stunning images generated by DALL-E AI</p>
      </div>

      <div className='mt-16'>

      </div>

      <div className='mt-10'>
        {
          loading ? (
            <div className="flex justify-center">
              <span className="loading loading-bars loading-lg"></span>
            </div>
          ) : (
            <>
              {search && (
                <h2 className='font-medium text-gray-600 text-xl mb-3'>Showing results for <span className='text-red-600'>{search}</span></h2>
              )}
              <div className="grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3">
                {search ? (
                  'dscsc'
                ) : (
                  allList.length > 0 && (
                    allList.map((list, i) => (
                      <div className="rounded-xl group relative shadow-card hover:shadow-cardhover card" key={i}>
                      <img className="w-full h-auto object-cover rounded-xl" src={list.photo} />
                        <div className="group-hover:flex flex-col max-h-[94.5%] hidden absolute bottom-0 left-0 right-0 bg-[#10131f] m-2 p-4 rounded-md">
                          <p className="text-white text-sm overflow-y-auto prompt">{list.prompt}</p>
                          <div className="mt-5 flex justify-between items-center gap-2">
                            <div className="flex items-center gap-2">
                              <div className="w-7 h-7 rounded-full object-cover bg-green-700 flex justify-center items-center text-white text-xs font-bold">{name[0]}</div>
                              <p className="text-white text-sm">{list.username}</p>
                            </div>
                            <button type="button" className="outline-none bg-transparent border-none">
                              <img src='' alt="download" className="w-6 h-6 object-contain invert" />
                            </button>
                          </div>
                        </div>
                      </div>
                    ))
                  )
                )}
              </div>
            </>
          )
        }
      </div>

    </section>
    <Footer />
    </>
  )
}
