import React, { useEffect, useState } from 'react'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import { useNavigate } from 'react-router-dom'

export default function Home() {
  const token = localStorage.getItem('token')
  const [loading, setIsLoading] = useState(false)
  const [allPosts, setAllPosts] = useState(null)
  const [search, setSearch] = useState('sdxax')
  const navigate = useNavigate()
  
  useEffect(() => {
    if (!token) {
      navigate('/')
    }
  })

  return (
    <>
    <Navbar />
    <section className='mx-5 md:container md:mx-auto md:px-48 mt-10 mb-10'>
      <div>
        <h1 className='font-extrabold text-3xl'>The Community Showcase</h1>
        <p className='mt-2 text-gray-500 text-xl'>Browse through of imaginative and visually stunning images generated by DALL-E AI</p>
      </div>

      <div className='mt-16'>

      </div>

      <div className='mt-10'>
        {
          loading ? (
            <div className="flex justify-center">
              <span className="loading loading-bars loading-lg"></span>
            </div>
          ) : (
            <>
              {search && (
                <h2 className='font-medium text-gray-600 text-xl mb-3'>Showing results for <span className='text-red-600'>{search}</span></h2>
              )}
              <div className="grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3">
                {search ? (
                  'dscsc'
                ) : (
                  'sscsca'
                )}
              </div>
            </>
          )
        }
      </div>

    </section>
    <Footer />
    </>
  )
}
